name:                chord-cloud-haskell
version:             0.1.0.0
github:              "wasabi315/chord-cloud-haskell"
license:             BSD3
author:              "wasabi315"
maintainer:          "wasabi.nvim.st@gmail.com"
copyright:           "2023 wasabi315"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/wasabi315/chord-cloud-haskell#readme>

dependencies:
- base >= 4.7 && < 5
- distributed-process
- network-transport-tcp
- binary
- haskeline
- transformers

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -O2

default-extensions:
- EmptyCase
- PostfixOperators
- TupleSections
- NamedFieldPuns
- RecordWildCards
- BangPatterns
- LambdaCase
- MultiWayIf
- ViewPatterns
- BinaryLiterals
- HexFloatLiterals
- GADTs
- RankNTypes
- TypeApplications
- PolyKinds
- ExistentialQuantification
- TypeOperators
- ConstraintKinds
- TypeFamilies
- ExplicitForAll
- PartialTypeSignatures
- KindSignatures
- NamedWildCards
- ScopedTypeVariables
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- MultiParamTypeClasses
- ConstrainedClassMethods
- InstanceSigs
- TypeSynonymInstances
- DeriveDataTypeable
- DeriveFoldable
- DeriveFunctor
- DeriveTraversable
- StandaloneDeriving
- DeriveLift
- DeriveGeneric
- DerivingStrategies
- DeriveAnyClass

library:
  source-dirs: src

executables:
  chord-cloud-haskell-exe:
    main: Main.hs
    source-dirs: app
    dependencies:
    - chord-cloud-haskell

tests:
  chord-cloud-haskell-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
    - chord-cloud-haskell
